export const TEST = 'TEST'

export const START_LOADING = 'START_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS'
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR'